name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
  contents: read

env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.app

jobs:
  build:
    name: Build for ${{ matrix.project }}
    runs-on: macos-13
    strategy:
      fail-fast: false
      matrix:
        project: ["production"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build for ${{ matrix.project }}
        run: make build-debug-${{ matrix.project }}
